baseURL = "https://www.raveen.ca"
defaultContentLanguage = "en"
languageCode = "en"

title = "Welcome!"

theme = ["gokarna", "hugo-shortcode-gallery"]

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "projects"
    url = "/projects/"
    name = "Projects"
    weight = 2

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "gallery"
    url = "/gallery/index/"
    name = "Gallery"
    weight = 3

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"
    name = "Posts"
    weight = 4

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 5

[params]
  # URL for the avatar on homepage
  avatarURL = "/home/avatar.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "My little piece of the internet"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = ""

